### ISSUE TITLE
The IDEA of invalid

### ISSUE THREAD

**Issue by yingweiqia** [Bezhuang/Pikachu-rainbow-fart#1]
If importing IDEA doesn't work, try converting WAV to MP3 and then changing the file name in manifest.json

**Comment by yingweiqia** [comment]
[Pikachu-rainbow-fart-IDEA.zip](https://github.com/Bezhuang/Pikachu-rainbow-fart/files/8526822/Pikachu-rainbow-fart-IDEA.zip)
This file is modified and IDEA is available

**Comment by Bezhuang** [comment]
Thanks for the advice

> [Pikachu-rainbow-fart-IDEA.zip](https://github.com/Bezhuang/Pikachu-rainbow-fart/files/8526822/Pikachu-rainbow-fart-IDEA.zip) This file is modified and IDEA is available

I've changed the audio format, thank you for the advice.
